using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Artillery;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Starlight.Artillery.UI;

[GenerateTypedNameReferences]
public sealed partial class ArtilleryConsoleWindow : FancyWindow
{
    public event Action? OnFirePressed;
    public event Action? OnToggleForwardPressed;
    public event Action? OnToggleRearPressed;

    #pragma warning disable RA0051
    [Dependency] private readonly IEntityManager _entMan = default!;
    public ArtilleryConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        FireButton.OnPressed += _ => OnFirePressed?.Invoke();
        RearBreechButton.OnPressed += _ => OnToggleRearPressed?.Invoke();
        FrontBreechButton.OnPressed += _ => OnToggleForwardPressed?.Invoke();
    }

    public void UpdateState(ArtilleryConsoleUiState state)
    {
        RearBreechContents.SetEntity(_entMan.GetEntity(state.RearBreechContains));
        ForwardBreechContents.SetEntity(_entMan.GetEntity(state.ForwardBreechContains));

        UpdateIndicators(state);
        RearBreechButton.Text = state.RearBreechOpen ? "Close Breech" : "Open Breech";
        FrontBreechButton.Text = state.ForwardBreechOpen ? "Close Breech" : "Open Breech";
        FireButton.Disabled = !state.CanFire;
    }
    private void UpdateIndicators(ArtilleryConsoleUiState msg)
    {
        var FilePath = "/Textures/_FarHorizons/Interface/FissionGenerator/indicator_lamps/";
        AssembledState.TexturePath = !msg.Assembled ? FilePath + "redlit.png" : FilePath + "greenlit.png";
        RearBreechStatus.TexturePath = msg.RearBreechOpen ? FilePath + "redlit.png" : FilePath + "greenlit.png";
        ForwardBreechStatus.TexturePath = msg.ForwardBreechOpen ? FilePath + "redlit.png" : FilePath + "greenlit.png";
        RearBreechLoaded.TexturePath =  !msg.ChargeValid ? FilePath + "redlit.png" : FilePath + "greenlit.png";
        ForwardBreechLoaded.TexturePath = msg.ForwardBreechContains is null ? FilePath + "redlit.png" : FilePath + "greenlit.png";
    }
}
